### PR TITLE
Topic new rasterwalk

### PR DESCRIPTION
**Pull request by dhowe**
Created a new sketch for ReCode:

"Random Walk Through Raster" by Frieder Nake, 1966
from Computer Graphics and Art - May, 1976 Vol. 1, No. 4 Pg 6-7

(Direct Translation)

URL (recode):  http://www.recodeproject.com/artwork/v1n4random-walk-through-raster
URL (demo):    http://rednoise.org/sketches/RasterWalk/

cheers,
-Daniel

### CODE REVIEW

**Comment by matthewepler** [comment]
Thanks! I'm in the middle of finals at school and will post this as soon as
I get a chance next week.

On Thu, Dec 13, 2012 at 5:25 AM, dhowe notifications@github.com wrote:

> Created a new sketch for ReCode:
> 
> "Random Walk Through Raster" by Frieder Nake, 1966
> from Computer Graphics and Art - May, 1976 Vol. 1, No. 4 Pg 6-7
> 
> (Direct Translation)
> 
> URL (recode):
> http://www.recodeproject.com/artwork/v1n4random-walk-through-raster
> URL (demo): http://rednoise.org/sketches/RasterWalk/
> 
> cheers,
> 
> ## -Daniel
> 
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/dhowe/ReCode_Project topic-new-rasterwalk
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/matthewepler/ReCode_Project/pull/17
> Commit Summary
> - initial checkin
> - FIX: MIT-Licence according to @K0F https://github.com/K0F see:
>   https://github.com/matthewepl…https://github.com/matthewepler/ReCode_Project/issues/7
> - FIX: MIT-Licence according to @K0F https://github.com/K0F see:
>   https://github.com/matthewepl…https://github.com/matthewepler/ReCode_Project/issues/7
> - Merge branch 'fixLicense' of
>   https://github.com/signalwerk/ReCode_Pro…https://github.com/signalwerk/ReCode_Project
> - Merge pull request #1https://github.com/dhowe/ReCode_Project/issues/1from signalwerk/fixLicense
> - Refactoring
> - initial commit
> - untracked pjs
> - added ignore
> - tmp test
> - removed unneeded files
> - removed extra file
> - Merge branch 'RasterWalk'
> - Topic branch for new sketch: RasterWalk
> 
> File Changes
> - _A_ daniel_howe/RasterWalk/.gitignore (1)
> - _A_ daniel_howe/RasterWalk/index.html (62)
> - _A_ daniel_howe/RasterWalk/rasterwalk.js (134)
> - _A_ daniel_howe/VoronoiRecode/Delaunay.pde (461)
> - _A_ daniel_howe/VoronoiRecode/VoronoiRecode.pde (144)
> 
> Patch Links
> - https://github.com/matthewepler/ReCode_Project/pull/17.patch
> - https://github.com/matthewepler/ReCode_Project/pull/17.diff
>   
>   —
>   Reply to this email directly or view it on GitHubhttps://github.com/matthewepler/ReCode_Project/pull/17.

## 

Matthew Epler
http://mepler.com

**Comment by dhowe** [comment]
Thanks Matthew, much appreciated. -DH

**Comment by matthewepler** [comment]
Merged!

**Comment by matthewepler** [comment]
The voronoi sketch throws an error in the update function at the lines calling the "clip2( edge.p1 ); and clip2( edge.p2 )."

I tried running it after deleting the digit '2,' and it seemed to run fine. Could you take a look and let me know what you'd like to do, please?

Looks awesome, btw.
ProcessingScreenSnapz001

**Comment by dhowe** [comment]
Your fix is correct (thanks!) -- do you want to check it in or should I?

**Comment by dhowe** [comment]
btw, how does one add these to the recode-project page (or do you have to do that?):

http://recodeproject.com/artwork/v1n4random-walk-through-raster  
  and
http://recodeproject.com/artwork/v3n2equidistant-space

cheers,
-DH

**Pull request merged**
