### PR TITLE
Licence upgrade (MIT)

### PR DESCRIPTION
**Pull request by K0F**
There are proper MIT licence headers added.. previously un-pushed second project _Diamond Theory_ is not finished yet.. working on direct recode, work in progress, thanks,

k.

### CODE REVIEW

**Comment by matthewepler** [comment]
k,

I went through the translations last night and made some changes to the headers. Please check yours and let me know if it is okay for you. 

Thanks so much!

Matt Epler

**Comment by K0F** [comment]
It seems to be ok in my case,
oh.. and that nice new features! I really like this democratic approach.. let's see what happens )

Thanks,
Krystof

**Comment by matthewepler** [comment]
Thanks, Krystof! I'd like to add you to the email list of core contributors
if that's okay with you. Can you send me an email so I have your regular
email address?

Thanks!
matthewepler@gmail.clom

On Wed, Dec 26, 2012 at 1:27 AM, Kryštof Pešek notifications@github.comwrote:

> It seems to be ok in my case,
> oh.. and that nice new features! I really like this democratic approach..
> let's see what happens )
> 
> Thanks,
> Krystof
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/matthewepler/ReCode_Project/pull/11#issuecomment-11681536.

## 

Matthew Epler
http://mepler.com

**Comment by K0F** [comment]
Thanks Matthew, I am glad I can contribute a little,
krystof.pesek@gmail.c0m

**Pull request closed without merging**
