### PR TITLE
Fix to clip2() vs clip() issue

### PR DESCRIPTION
**Pull request by dhowe**
Fix to clip2() vs clip() issue
Should be set to publish
thanks,
-DH

### CODE REVIEW

**Comment by matthewepler** [comment]
Thanks, Daniel! I know I dropped the ball on this one, but would you mind
trying out the new "Add Translation" feature? You'd be the first to use it,
and I could use some feedback.

Go to the original piece on the website, and you'll find the "Add
Translation" button just below the original image.

If you don't have time just let me know and I'll post yours for you by the
end of the day.

Matt Epler

On Sun, Dec 23, 2012 at 12:22 AM, dhowe notifications@github.com wrote:

> Fix to clip2() vs clip() issue
> Should be set to publish
> thanks,
> 
> ## -DH
> 
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/dhowe/ReCode_Project master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/matthewepler/ReCode_Project/pull/18
> Commit Summary
> - fixed problem with clip2
> - Merge remote-tracking branch 'upstream/master'
> 
> File Changes
> - _M_ daniel_howe/VoronoiRecode/VoronoiRecode.pde (4)
> 
> Patch Links
> - https://github.com/matthewepler/ReCode_Project/pull/18.patch
> - https://github.com/matthewepler/ReCode_Project/pull/18.diff
>   
>   —
>   Reply to this email directly or view it on GitHubhttps://github.com/matthewepler/ReCode_Project/pull/18.

## 

Matthew Epler
http://mepler.com

**Comment by dhowe** [comment]
Hi Matt,
Happy Holidays!
When I trued to submit a translation, I get the error below
cheers,
-Daniel

**Comment by matthewepler** [comment]
I don't see an error in your message. Could you send it again, please?

**Comment by dhowe** [comment]
I just took a screenshot --- is it not showing up for you?
-Daniel

Begin forwarded message:

> From: Daniel Howe daniel.c.howe@gmail.com
> Date: 25 December 2012 3:17:20 PM GMT+08:00
> To: matthewepler/ReCode_Project reply@reply.github.com
> Subject: Re: Add Translation Problem
> 
> Hi Matt,
> Happy Holidays!
> When I trued to submit a translation, I get the error below
> cheers,
> -Daniel
> 
> On 23 Dec 2012, at 11:15 PM, Matthew Epler wrote:
> 
> > Thanks, Daniel! I know I dropped the ball on this one, but would you mind 
> > trying out the new "Add Translation" feature? You'd be the first to use it, 
> > and I could use some feedback. 
> > 
> > Go to the original piece on the website, and you'll find the "Add 
> > Translation" button just below the original image. 
> > 
> > If you don't have time just let me know and I'll post yours for you by the 
> > end of the day. 
> > 
> > Matt Epler 
> >

**Comment by dhowe** [comment]
When I try it now, I get:

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by dhowe** [comment]
Let me know if I should try again...
cheers,
-Daniel

**Comment by matthewepler** [comment]
Should work now. Had to add S3 permissions to the heroku app. Let me know
if it works!

Also, I'd like to add you to the email list for core contributors so you
can be a part of any discussions related to the future of the project. Is
that okay? If so, just send me an email and I'll add you:
matthewepler@gmail.com

Thanks!

Matt Epler

On Fri, Dec 28, 2012 at 4:54 AM, dhowe notifications@github.com wrote:

> Let me know if I should try again...
> cheers,
> -Daniel
> On 23 Dec 2012, at 11:15 PM, Matthew Epler wrote:
> 
> > Thanks, Daniel! I know I dropped the ball on this one, but would you
> > mind
> > trying out the new "Add Translation" feature? You'd be the first to use
> > it,
> > and I could use some feedback.
> > 
> > Go to the original piece on the website, and you'll find the "Add
> > Translation" button just below the original image.
> > 
> > If you don't have time just let me know and I'll post yours for you by
> > the
> > end of the day.
> > 
> > Matt Epler
> > 
> > On Sun, Dec 23, 2012 at 12:22 AM, dhowe notifications@github.com
> > wrote:
> > 
> > > Fix to clip2() vs clip() issue
> > > Should be set to publish
> > > thanks,
> > > 
> > > ## -DH
> > > 
> > > You can merge this Pull Request by running:
> > > 
> > > git pull https://github.com/dhowe/ReCode_Project master
> > > 
> > > Or view, comment on, or merge it at:
> > > 
> > > https://github.com/matthewepler/ReCode_Project/pull/18
> > > Commit Summary
> > > - fixed problem with clip2
> > > - Merge remote-tracking branch 'upstream/master'
> > > 
> > > File Changes
> > > - _M_ daniel_howe/VoronoiRecode/VoronoiRecode.pde (4)
> > > 
> > > Patch Links
> > > - https://github.com/matthewepler/ReCode_Project/pull/18.patch
> > > - https://github.com/matthewepler/ReCode_Project/pull/18.diff
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/matthewepler/ReCode_Project/pull/18>.
> > 
> > ## 
> > 
> > Matthew Epler
> > http://mepler.com
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/matthewepler/ReCode_Project/pull/18#issuecomment-11728666.

## 

Matthew Epler
http://mepler.com

**Pull request closed without merging**
