### PR TITLE
"Equidistant Space" by Peter Milojevic

### PR DESCRIPTION
**Pull request by dhowe**
Direct Translation, from Computer Graphics and Art vol3 no2 pg 11

Online at: http://rednoise.org/sketches/VoronoiRecode/

cheers,
Daniel Howe

### CODE REVIEW

**Comment by signalwerk** [comment]
I did a pull request on your commit
For Details: https://github.com/dhowe/ReCode_Project/pull/1

**Comment by dhowe** [comment]
I consolidated a few of the classes to keep the external code separate (now just two files)...

**Comment by signalwerk** [comment]
Oh! Sorry. I didn't understand that the other two files are also from Marcus Appel. But now everything is easy understandable and seams perfect to me. Thanks a lot for the clarification!

**Comment by matthewepler** [comment]
Thanks, Daniel! I'm finishing up final projects at school and will get this
up as soon as I can next week.

On Tue, Dec 11, 2012 at 5:18 PM, Stefan Huber notifications@github.comwrote:

> Oh! Sorry. I didn't understand that the other two files are also from
> Marcus Appel. But now everything is easy understandable and seams perfect
> to me. Thanks a lot for the clarification!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/matthewepler/ReCode_Project/pull/16#issuecomment-11267130.

## 

Matthew Epler
http://mepler.com

**Pull request merged**
